// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200919134808_primeira-migracao")]
    partial class primeiramigracao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60) CHARACTER SET utf8mb4")
                        .HasMaxLength(60);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eca959fb-e684-4c13-97df-27dfb887b3b3"),
                            CreateAt = new DateTime(2020, 9, 19, 10, 48, 8, 336, DateTimeKind.Local).AddTicks(8500),
                            Email = "adm@adm.com",
                            Name = "Administrador",
                            Role = "Administrator",
                            UpdateAt = new DateTime(2020, 9, 19, 10, 48, 8, 338, DateTimeKind.Local).AddTicks(6359)
                        },
                        new
                        {
                            Id = new Guid("45ba8fc0-db73-43e8-a2d4-f0115f9eb5f0"),
                            CreateAt = new DateTime(2020, 9, 19, 10, 48, 8, 338, DateTimeKind.Local).AddTicks(7290),
                            Email = "user@example.com",
                            Name = "Cliente",
                            Role = "Client",
                            UpdateAt = new DateTime(2020, 9, 19, 10, 48, 8, 338, DateTimeKind.Local).AddTicks(7312)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
